/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ellie_bolt_jni_rtlsdr_RTLSDR */

#ifndef _Included_net_ellie_bolt_jni_rtlsdr_RTLSDR
#define _Included_net_ellie_bolt_jni_rtlsdr_RTLSDR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    getDeviceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_getDeviceCount
  (JNIEnv *, jclass);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    getDeviceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_getDeviceName
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nOpen
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nOpen
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetXtalFreq
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetXtalFreq
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nWriteEeprom
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nWriteEeprom
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nReadEeprom
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nReadEeprom
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetCenterFreq
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetCenterFreq
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nGetCenterFreq
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nGetCenterFreq
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetFreqCorrection
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetFreqCorrection
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nGetFreqCorrection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nGetFreqCorrection
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nGetTunerType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nGetTunerType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nGetTunerGains
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nGetTunerGains
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetTunerGain
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetTunerGain
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetTunerBandwidth
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetTunerBandwidth
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nGetTunerGain
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nGetTunerGain
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetTunerIFGain
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetTunerIFGain
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetTunerGainMode
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetTunerGainMode
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetSampleRate
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetSampleRate
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nGetSampleRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nGetSampleRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetTestmode
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetTestmode
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetAgcMode
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetAgcMode
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetDirectSampling
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetDirectSampling
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nGetDirectSampling
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nGetDirectSampling
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetOffsetTuning
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetOffsetTuning
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nGetOffsetTuning
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nGetOffsetTuning
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetBiasTee
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetBiasTee
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nSetBiasTeeGpio
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nSetBiasTeeGpio
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nResetBuffer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nResetBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_ellie_bolt_jni_rtlsdr_RTLSDR
 * Method:    nReadSync
 * Signature: (J[BI[I)I
 */
JNIEXPORT jint JNICALL Java_net_ellie_bolt_jni_rtlsdr_RTLSDR_nReadSync
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
